# Generated by Django 3.0.6 on 2020-05-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth', models.DateField()),
                ('company', models.CharField(choices=[('google', 'Google'), ('yandex', 'Yandex'), ('epam', 'Epam')], max_length=150)),
                ('position', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=15)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c#', 'C#'), ('c++', 'C++')], default='python', max_length=10)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
