version: "3"

services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
     - ./nginx-conf.d:/etc/nginx/conf.d/
    ports: 
      - "80:80"
  mysite:
    build: .
    image: diplom
    ports: 
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app


