# Generated by Django 3.0.6 on 2020-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('2', 'успешно'), ('1', 'неуспешно')], default='1', max_length=20),
        ),
    ]
