# Generated by Django 3.0.6 on 2020-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('УСП', 'успешно'), ('НЕУСП', 'неуспешно')], default='УСП', max_length=20),
        ),
        migrations.AlterField(
            model_name='input',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
