# Generated by Django 3.0.6 on 2020-05-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200531_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
