# Generated by Django 3.0.6 on 2020-05-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200529_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userss',
            old_name='user',
            new_name='socialauth',
        ),
    ]
