# Generated by Django 3.0.6 on 2020-06-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200601_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userss',
        ),
    ]
