# Generated by Django 3.0.6 on 2020-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200530_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
