# Generated by Django 3.0.7 on 2020-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
