# Generated by Django 3.0.6 on 2020-05-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200531_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
